import { Product, Coupon, CustomerProfile, UserSubscription, Order, SupportTicket, FinancialMetric, Review, BangladeshPaymentMethod, HeroSlide } from '@/types';

export const MOCK_PAYMENT_METHODS: BangladeshPaymentMethod[] = [
  {
    id: 'pm_bkash_01',
    name: 'bKash Personal',
    type: 'bkash',
    accountNumber: '01712-345678',
    accountType: 'Personal',
    qrCodeImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=01712345678',
    instructions: 'Go to your bKash App > Send Money > Enter the number above > Enter amount in BDT > Complete and copy the TrxID.',
    bdtRate: 125,
    isActive: true,
    showQrCode: true,
    color: '#e2136e',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pm_nagad_01',
    name: 'Nagad Personal',
    type: 'nagad',
    accountNumber: '01912-345678',
    accountType: 'Personal',
    qrCodeImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=01912345678',
    instructions: 'Go to your Nagad App > Send Money > Enter the number above > Submit transaction and copy the TrxID.',
    bdtRate: 125,
    isActive: true,
    showQrCode: true,
    color: '#f7931e',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pm_rocket_01',
    name: 'Rocket Personal',
    type: 'rocket',
    accountNumber: '01812-345678-9',
    accountType: 'Personal',
    qrCodeImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=018123456789',
    instructions: 'Go to your Rocket App or dial *322# > Send Money to this 12-digit number > Enter the TrxID below.',
    bdtRate: 125,
    isActive: true,
    showQrCode: true,
    color: '#8c3494',
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    code: 'NEXUS20',
    discountPercent: 20,
    description: '20% off all individual & team subscriptions',
    isSpecialOffer: true,
    offerTag: '⚡ FLASH SALE',
    offerTitle: 'Instant 20% Off Storewide Discount',
    offerImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    type: 'discount',
  },
  {
    code: 'VIP50',
    discountPercent: 50,
    description: '50% discount on annual premium AI & streaming plans',
    minOrderAmount: 40,
    isSpecialOffer: true,
    offerTag: '🔥 50% OFF VIP',
    offerTitle: 'VIP Annual Pass 50% Mega Discount',
    offerImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    type: 'special_deal',
  },
  {
    code: 'GIVEAWAY100',
    discountPercent: 100,
    description: '100% Free 1-Month ChatGPT Plus / Claude Slot Giveaway Code',
    isSpecialOffer: true,
    offerTag: '🎁 FREE GIVEAWAY',
    offerTitle: 'Community Monthly Premium Giveaway Code',
    offerImage: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
    type: 'giveaway',
    requiredTasks: [
      { id: 'task_tg', label: 'Join Official Telegram Channel', url: 'https://t.me/keyoon_deals', isRequired: true },
      { id: 'task_fb', label: 'Follow Keyoon Facebook Page', url: 'https://facebook.com/keyoon', isRequired: true },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    slug: 'chatgpt-plus',
    category: 'ai',
    tagline: 'GPT-4o, Canvas, DALL-E & Advanced Voice',
    description: 'Official OpenAI Plus with priority access and full model capabilities.',
    logo: '/images/cards/chatgpt-plus.jpg',
    images: [
      'https://i.giphy.com/f0VbswUmSY6X1cBz4C.gif',
      '/images/cards/chatgpt-plus.jpg',
      'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-emerald-600/30 to-zinc-900',
    rating: 4.98,
    reviewCount: 4120,
    deliveryType: 'instant_bot',
    accountType: 'private_account',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['GPT-4o & Canvas access', 'Advanced Voice Mode', 'Full term warranty'],
    specs: {
      screens: 2,
      quality: 'Ultra High Speed',
      warranty: 'Full Period Replacement',
      platforms: ['Web', 'iOS', 'Android', 'macOS'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '1_month', label: '1 Month', price: 999, originalPrice: 2500, discountPercentage: 60 },
      { duration: '3_months', label: '3 Months', price: 2749, originalPrice: 7500, discountPercentage: 63, isPopular: true },
      { duration: '6_months', label: '6 Months', price: 4999, originalPrice: 15000, discountPercentage: 66 },
      { duration: '12_months', label: '12 Months', price: 8749, originalPrice: 30000, discountPercentage: 70 },
    ],
    stockCount: 84,
    instructions: [
      'Copy credentials from your Vault.',
      'Log in at chatgpt.com.',
      'Start using GPT-4o Plus immediately.'
    ]
  },
  {
    id: 'gemini-advanced',
    name: 'Gemini Advanced',
    slug: 'gemini-advanced',
    category: 'ai',
    tagline: 'Gemini 2.0 Pro + 2TB Google One Storage',
    description: 'Google next-gen AI with 2M token context window and 2TB cloud storage.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/13YPREdAEAHpCoo1SA.gif',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-blue-600/30 to-zinc-900',
    rating: 4.95,
    reviewCount: 2840,
    deliveryType: 'instant_bot',
    accountType: 'direct_upgrade',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['Gemini 2.0 Flash & Pro', '2 Million token context', '2TB Google One Storage'],
    specs: {
      screens: 5,
      quality: '2M Token Context',
      warranty: 'Full Period Replacement',
      platforms: ['Web', 'Android', 'iOS', 'Workspace'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '1_month', label: '1 Month', price: 874, originalPrice: 2500, discountPercentage: 65 },
      { duration: '3_months', label: '3 Months', price: 2374, originalPrice: 7500, discountPercentage: 68 },
      { duration: '6_months', label: '6 Months', price: 4374, originalPrice: 15000, discountPercentage: 70, isPopular: true },
      { duration: '12_months', label: '12 Months', price: 7499, originalPrice: 30000, discountPercentage: 75 },
    ],
    stockCount: 62,
    instructions: [
      'Click invitation link in your Vault.',
      'Accept Google One membership.',
      'Verify Advanced status at gemini.google.com.'
    ]
  },
  {
    id: 'claude-pro',
    name: 'Claude 3.5 Pro',
    slug: 'claude-pro',
    category: 'ai',
    tagline: 'Anthropic Claude 3.5 Sonnet & Artifacts',
    description: 'Premier AI assistant for engineering, architecture, and coding.',
    logo: '/images/cards/claude-pro.jpg',
    images: [
      'https://i.giphy.com/CVtNe84hhYF9u.gif',
      '/images/cards/claude-pro.jpg',
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-amber-600/30 to-zinc-900',
    rating: 4.99,
    reviewCount: 3950,
    deliveryType: 'instant_bot',
    accountType: 'private_account',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['Claude 3.5 Sonnet model', '5x peak usage limits', 'Interactive Artifacts workspace'],
    specs: {
      screens: 2,
      quality: 'Artifacts Enabled',
      warranty: 'Full Replacement',
      platforms: ['Web', 'iOS', 'Android'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '1_month', label: '1 Month', price: 1060, originalPrice: 2500, discountPercentage: 58 },
      { duration: '3_months', label: '3 Months', price: 2999, originalPrice: 7500, discountPercentage: 60, isPopular: true },
      { duration: '6_months', label: '6 Months', price: 5624, originalPrice: 15000, discountPercentage: 62 },
      { duration: '12_months', label: '12 Months', price: 9999, originalPrice: 30000, discountPercentage: 66 },
    ],
    stockCount: 45,
    instructions: [
      'Get login details from Vault.',
      'Sign in at claude.ai.',
      'Enjoy Claude 3.5 Pro.'
    ]
  },
  {
    id: 'netflix-4k-uhd',
    name: 'Netflix 4K UHD',
    slug: 'netflix-4k-uhd',
    category: 'streaming',
    tagline: '4K Ultra HD, Dolby Atmos & Dedicated Profile',
    description: 'Watch all films and series in 4K HDR with dedicated PIN-locked profile.',
    logo: '/images/cards/netflix-4k.jpg',
    images: [
      'https://i.giphy.com/l41Y9SKrl3kLVamfC.gif',
      '/images/cards/netflix-4k.jpg',
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-red-600/30 to-zinc-900',
    rating: 4.94,
    reviewCount: 9240,
    deliveryType: 'instant_bot',
    accountType: 'private_account',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['4K Ultra HD & Dolby Atmos', 'Dedicated PIN profile', 'TV & mobile compatible'],
    specs: {
      screens: 4,
      quality: '4K Ultra HD',
      warranty: 'Full Period Replacement',
      platforms: ['Smart TV', 'Apple TV', 'Mobile', 'Web'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '1_month', label: '1 Month', price: 624, originalPrice: 2875, discountPercentage: 78 },
      { duration: '3_months', label: '3 Months', price: 1749, originalPrice: 8620, discountPercentage: 80, isPopular: true },
      { duration: '6_months', label: '6 Months', price: 3249, originalPrice: 17240, discountPercentage: 81 },
      { duration: '12_months', label: '12 Months', price: 5874, originalPrice: 34480, discountPercentage: 83 },
    ],
    stockCount: 120,
    instructions: [
      'Check profile name and PIN in Vault.',
      'Log into Netflix.',
      'Select designated profile.'
    ]
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    slug: 'youtube-premium',
    category: 'streaming',
    tagline: 'Zero Ads, Background Play & YouTube Music',
    description: 'Ad-free playback across all devices plus high-fidelity music streaming.',
    logo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/TgMAmoaliiMthuz4zM.gif',
      'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-rose-600/30 to-zinc-900',
    rating: 4.97,
    reviewCount: 6510,
    deliveryType: 'slot_invite',
    accountType: 'direct_upgrade',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['100% Ad-free viewing', 'Background audio playback', 'YouTube Music included'],
    specs: {
      screens: 10,
      quality: 'Ad-Free 4K',
      warranty: 'Full Term Warranty',
      platforms: ['TV', 'Mobile', 'Web'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '3_months', label: '3 Months', price: 1249, originalPrice: 5240, discountPercentage: 76 },
      { duration: '6_months', label: '6 Months', price: 2249, originalPrice: 10490, discountPercentage: 78, isPopular: true },
      { duration: '12_months', label: '12 Months', price: 3749, originalPrice: 20980, discountPercentage: 82 },
    ],
    stockCount: 95,
    instructions: [
      'Enter Google email at checkout.',
      'Accept invitation link.',
      'Enjoy YouTube Premium.'
    ]
  },
  {
    id: 'spotify-premium',
    name: 'Spotify Premium',
    slug: 'spotify-premium',
    category: 'streaming',
    tagline: 'Ad-Free 320kbps & Offline Downloads',
    description: 'Unlimited skips and offline music on your personal account.',
    logo: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/eLWxHo6CahrtnFBea3.gif',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-emerald-600/30 to-zinc-900',
    rating: 4.96,
    reviewCount: 8120,
    deliveryType: 'slot_invite',
    accountType: 'direct_upgrade',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['High bitrate audio', 'No ads between songs', 'Offline download support'],
    specs: {
      screens: 3,
      quality: '320kbps Extreme Audio',
      warranty: 'Full Period Replacement',
      platforms: ['Mobile', 'Desktop', 'Speaker'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '3_months', label: '3 Months', price: 1124, originalPrice: 4490, discountPercentage: 75 },
      { duration: '6_months', label: '6 Months', price: 1999, originalPrice: 8990, discountPercentage: 77, isPopular: true },
      { duration: '12_months', label: '12 Months', price: 3374, originalPrice: 17980, discountPercentage: 81 },
    ],
    stockCount: 88,
    instructions: [
      'Receive Spotify invite link.',
      'Join designated family plan.',
      'Verify Premium benefits on Spotify.'
    ]
  },
  {
    id: 'cursor-pro',
    name: 'Cursor Pro',
    slug: 'cursor-pro',
    category: 'dev',
    tagline: 'Fast Claude 3.5 & GPT-4o Code Editor',
    description: 'AI-first code editor with multi-file reasoning, fast completions, and full workspace context.',
    logo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/zOvBKUUEERdNm.gif',
      '/images/hero-dev-code.jpg',
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-cyan-600/30 to-zinc-900',
    rating: 4.99,
    reviewCount: 2150,
    deliveryType: 'instant_bot',
    accountType: 'private_account',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['500 Fast Claude 3.5 requests', 'Multi-file Composer', 'Unlimited slow requests'],
    specs: {
      screens: 2,
      quality: 'Fast Claude 3.5 Sonnet',
      warranty: 'Full Period Replacement',
      platforms: ['macOS', 'Windows', 'Linux'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '1_month', label: '1 Month', price: 1124, originalPrice: 2500, discountPercentage: 55 },
      { duration: '3_months', label: '3 Months', price: 3124, originalPrice: 7500, discountPercentage: 58, isPopular: true },
      { duration: '6_months', label: '6 Months', price: 5874, originalPrice: 15000, discountPercentage: 60 },
      { duration: '12_months', label: '12 Months', price: 10624, originalPrice: 30000, discountPercentage: 64 },
    ],
    stockCount: 38,
    instructions: [
      'Copy Cursor Pro credentials from Vault.',
      'Log into Cursor IDE.',
      'Start using unlimited fast completions.'
    ]
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    slug: 'adobe-creative-cloud',
    category: 'productivity',
    tagline: '20+ Desktop Apps + Firefly AI Credits',
    description: 'Full Creative Cloud suite with Photoshop, Illustrator, Premiere Pro, After Effects, and 100GB cloud storage.',
    logo: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/jRZaSAayLWMRFwo3Ng.gif',
      '/images/hero-creative-vpn.jpg',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-red-600/30 to-zinc-900',
    rating: 4.93,
    reviewCount: 1980,
    deliveryType: 'slot_invite',
    accountType: 'direct_upgrade',
    deliveryTimeEstimate: 'Instant (< 45s)',
    features: ['Photoshop, Illustrator, Premiere', 'Firefly Generative AI', '100GB Adobe Cloud'],
    specs: {
      screens: 2,
      quality: 'All 20+ Desktop Apps',
      warranty: 'Full Replacement',
      platforms: ['macOS', 'Windows', 'iPad'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '3_months', label: '3 Months', price: 3749, originalPrice: 22490, discountPercentage: 83 },
      { duration: '6_months', label: '6 Months', price: 6874, originalPrice: 44990, discountPercentage: 84, isPopular: true },
      { duration: '12_months', label: '12 Months', price: 11874, originalPrice: 89980, discountPercentage: 86 },
    ],
    stockCount: 29,
    instructions: [
      'Provide your Adobe ID at checkout.',
      'Accept team organization invitation.',
      'All apps will activate automatically in Creative Cloud desktop app.'
    ]
  },
  {
    id: 'nordvpn-complete',
    name: 'NordVPN Complete',
    slug: 'nordvpn-complete',
    category: 'vpn_security',
    tagline: 'Encrypted VPN + Threat Protection + 1TB Cloud',
    description: 'High-speed encrypted VPN across 111 countries with malware protection and cross-platform password manager.',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://i.giphy.com/077i6AULCXc0FKTj9s.gif',
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80'
    ],
    bannerGradient: 'from-blue-600/30 to-zinc-900',
    rating: 4.97,
    reviewCount: 4200,
    deliveryType: 'instant_bot',
    accountType: 'private_account',
    deliveryTimeEstimate: 'Instant (< 30s)',
    features: ['6,000+ Fast Servers in 111 Countries', 'Threat Protection Pro', '10 simultaneous devices'],
    specs: {
      screens: 10,
      quality: 'Ultra 10Gbps Speed',
      warranty: 'Full Period Replacement',
      platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
      region: 'Global'
    },
    pricingTiers: [
      { duration: '6_months', label: '6 Months', price: 2124, originalPrice: 8990, discountPercentage: 76 },
      { duration: '12_months', label: '12 Months', price: 3624, originalPrice: 17980, discountPercentage: 80, isPopular: true },
    ],
    stockCount: 65,
    instructions: [
      'Copy NordVPN login from Vault.',
      'Sign in at nordvpn.com or in NordVPN app.',
      'Connect to any server worldwide.'
    ]
  }
];

export const INITIAL_USER_PROFILE: CustomerProfile = {
  id: 'guest',
  name: 'Guest',
  email: '',
  avatar: '',
  role: 'customer',
  joinedDate: new Date().toISOString().split('T')[0],
  lifetimeSpend: 0,
  activeSubscriptionsCount: 0,
  preferredCurrency: 'USD',
  emailAlertsEnabled: true,
  autoRenewEnabled: true,
};

export const INITIAL_USER_SUBSCRIPTIONS: UserSubscription[] = [
  {
    id: 'sub_chatgpt_01',
    orderId: 'ord_9901',
    productId: 'chatgpt-plus',
    productName: 'ChatGPT Plus',
    productLogo: '/images/cards/chatgpt-plus.jpg',
    planDuration: '3_months',
    durationLabel: '3 Months',
    pricePaid: 21.99,
    status: 'active',
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    autoRenew: true,
    autoRenewReminderDays: 3,
    accountType: 'private_account',
    warrantyValidUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'card_stripe',
    credentials: {
      email: 'alex.vance+ai@subnexus-vault.io',
      password: 'NxP$92!kL8mQw1',
      pinCode: '8492',
      notes: 'Private Dedicated Account. Direct login at chatgpt.com',
    },
  },
  {
    id: 'sub_netflix_02',
    orderId: 'ord_9902',
    productId: 'netflix-4k-uhd',
    productName: 'Netflix 4K UHD',
    productLogo: '/images/cards/netflix-4k.jpg',
    planDuration: '6_months',
    durationLabel: '6 Months',
    pricePaid: 25.99,
    status: 'active',
    startDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 165 * 24 * 60 * 60 * 1000).toISOString(),
    autoRenew: false,
    autoRenewReminderDays: 3,
    accountType: 'private_account',
    warrantyValidUntil: new Date(Date.now() + 165 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'crypto_usdt',
    credentials: {
      email: 'nf-pool-881@subnexus-vip.com',
      password: 'Nflx*99$Vault!',
      pinCode: '4401',
      profileName: 'Slot 3 - Alex',
      notes: 'Use Profile: Slot 3 - Alex with PIN 4401. 4K HDR enabled.',
    },
  },
  {
    id: 'sub_cursor_03',
    orderId: 'ord_9903',
    productId: 'cursor-pro',
    productName: 'Cursor Pro',
    productLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    planDuration: '1_month',
    durationLabel: '1 Month',
    pricePaid: 8.99,
    status: 'expiring_soon',
    startDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    autoRenew: true,
    autoRenewReminderDays: 3,
    accountType: 'private_account',
    warrantyValidUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'card_stripe',
    credentials: {
      email: 'alex.vance+dev@subnexus-vault.io',
      password: 'Dev*Cursor$2026',
      notes: 'Sign into Cursor IDE with these credentials to activate fast requests.',
    },
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_9901',
    orderNumber: 'SNX-89124',
    userId: 'usr_88231',
    userEmail: 'alex.vance@subnexus.dev',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        productId: MOCK_PRODUCTS[0].id,
        productName: MOCK_PRODUCTS[0].name,
        productLogo: MOCK_PRODUCTS[0].logo,
        duration: '3_months',
        durationLabel: '3 Months',
        price: 21.99,
        quantity: 1,
      },
    ],
    subtotal: 21.99,
    discount: 0,
    total: 21.99,
    paymentMethod: 'card_stripe',
    paymentStatus: 'paid',
    deliveryStatus: 'delivered',
    generatedSubscriptionIds: ['sub_chatgpt_01'],
  },
  {
    id: 'ord_9902',
    orderNumber: 'SNX-89155',
    userId: 'usr_88231',
    userEmail: 'alex.vance@subnexus.dev',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        productId: MOCK_PRODUCTS[3].id,
        productName: MOCK_PRODUCTS[3].name,
        productLogo: MOCK_PRODUCTS[3].logo,
        duration: '6_months',
        durationLabel: '6 Months',
        price: 25.99,
        quantity: 1,
      },
    ],
    subtotal: 25.99,
    discount: 0,
    total: 25.99,
    paymentMethod: 'crypto_usdt',
    paymentStatus: 'paid',
    deliveryStatus: 'delivered',
    generatedSubscriptionIds: ['sub_netflix_02'],
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'tkt_101',
    ticketNumber: 'TKT-7821',
    userId: 'usr_88231',
    userEmail: 'alex.vance@subnexus.dev',
    subject: 'Requesting extra OpenAI workspace seats',
    category: 'general',
    status: 'open',
    priority: 'high',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: 'msg_1',
        sender: 'user',
        senderName: 'Alex Vance',
        content: 'Hi! Can I upgrade my ChatGPT Plus tier to a team pool for 5 seats?',
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg_2',
        sender: 'agent',
        senderName: 'Keyoon Bot Ops',
        content: 'Hello Alex! Absolutely. We can allocate a dedicated 5-seat workspace from our enterprise pool at $32.99/mo. Let us know if you want us to provision it.',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
];

export const INITIAL_FINANCIAL_METRICS: FinancialMetric = {
  mrr: 0,
  arr: 0,
  netRevenueToday: 0,
  activeSubscribers: 0,
  churnRate: 0,
  averageOrderValue: 0,
  growthMoM: 0,
  lifetimeValue: 0,
};

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    userId: 'usr_88231',
    userName: 'Alex Vance',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    userEmail: 'alex.vance@subnexus.dev',
    productId: 'chatgpt-plus',
    productName: 'ChatGPT Plus',
    productLogo: '/images/cards/chatgpt-plus.jpg',
    rating: 5,
    title: 'Instant 15-second delivery and GPT-4o works flawlessly!',
    comment: 'Was skeptical at first about wholesale rates, but credentials showed up in my Vault in less than 20 seconds. GPT-4o Canvas and Voice mode work seamlessly on web and iOS app. Saved over $140 this year!',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 42,
    likedBy: [],
    planDuration: '12 Months',
  },
  {
    id: 'rev_2',
    userId: 'usr_99104',
    userName: 'Elena Rostova',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    userEmail: 'elena.rostova@designlab.io',
    productId: 'claude-pro',
    productName: 'Claude 3.5 Pro',
    productLogo: '/images/cards/claude-pro.jpg',
    rating: 5,
    title: 'Claude 3.5 Sonnet is a game changer for our engineering team',
    comment: 'The Artifacts UI and 200k context window are indispensable. Keyoon automated renewals have made subscription management zero maintenance. Customer service replies in minutes.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 29,
    likedBy: [],
    planDuration: '6 Months',
  },
  {
    id: 'rev_3',
    userId: 'usr_44012',
    userName: 'Marcus Chen',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    userEmail: 'marcus.chen@techstream.com',
    productId: 'cursor-pro',
    productName: 'Cursor Pro',
    productLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Unlimited fast Opus & Sonnet completions in IDE',
    comment: 'As a full-stack dev, Cursor Pro is 10x better than standard Copilot. Got the 3-month package at 60% discount. Everything activated with a single click. Highly recommended!',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 38,
    likedBy: [],
    planDuration: '3 Months',
  },
  {
    id: 'rev_4',
    userId: 'usr_55192',
    userName: 'Sarah Jenkins',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    userEmail: 'sarah.j@cinema-vault.net',
    productId: 'netflix-4k',
    productName: 'Netflix 4K UHD',
    productLogo: '/images/cards/netflix-4k.jpg',
    rating: 5,
    title: 'Crystal clear 4K Dolby Atmos with private locked PIN',
    comment: 'Dedicated profile with my own PIN code. No profile collisions or kicked devices. Streaming Dolby Vision in 4K without any interruptions. Best streaming deal on the web.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 51,
    likedBy: [],
    planDuration: '12 Months',
  },
  {
    id: 'rev_5',
    userId: 'usr_33890',
    userName: 'David Miller',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    userEmail: 'david.m@creative-flow.agency',
    productId: 'adobe-cc',
    productName: 'Adobe Creative Cloud',
    productLogo: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Official Adobe account with 100GB Cloud Storage',
    comment: 'Direct email invitation received in 2 minutes. Photoshop, Illustrator, Premiere Pro and Firefly generative credits all working 100% on Mac and iPad.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 24,
    likedBy: [],
    planDuration: '12 Months',
  },
  {
    id: 'rev_6',
    userId: 'usr_77610',
    userName: 'Liam Thorne',
    userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    userEmail: 'liam.thorne@crypto-hub.io',
    productId: 'gemini-advanced',
    productName: 'Google Gemini Advanced',
    productLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    title: '2 Million Token Context Window is unmatched',
    comment: 'Uploaded entire 800-page financial PDF reports and Gemini parsed them effortlessly. Seamless integration with Google Docs & Drive. Instant credentials in Vault.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 19,
    likedBy: [],
    planDuration: '3 Months',
  },
  {
    id: 'rev_7',
    userId: 'usr_22419',
    userName: 'Chloe Dubois',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    userEmail: 'chloe.dubois@soundlab.fr',
    productId: 'spotify-premium',
    productName: 'Spotify Premium',
    productLogo: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Ad-free high fidelity streaming across all my speakers',
    comment: 'Transferred all my playlists and liked songs seamlessly. Offline downloads work on phone and car. Super smooth purchase experience with Apple Pay.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 31,
    likedBy: [],
    planDuration: '12 Months',
  },
  {
    id: 'rev_8',
    userId: 'usr_66311',
    userName: 'Vikram Patel',
    userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    userEmail: 'vikram.patel@security-ops.com',
    productId: 'nordvpn-complete',
    productName: 'NordVPN Complete',
    productLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Top tier speeds and dedicated IP functionality',
    comment: '10 simultaneous devices connected with 850Mbps download speeds. Threat protection and NordPass included. Renewal reminder system in dashboard is very handy.',
    verifiedPurchase: true,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 17,
    likedBy: [],
    planDuration: '12 Months',
  },
];

export const MOCK_HERO_SLIDES: HeroSlide[] = [
  {
    id: 'hero_1',
    sub: 'Save Up to 80% on Official Digital Plans',
    title: 'Premium Subscriptions at Wholesale Rates',
    tag: 'INSTANT 30S DELIVERY',
    bgImage: '/images/hero-vault.jpg',
    ctaText: 'Explore Catalog',
    ctaLink: '#catalog',
    order: 1,
  },
  {
    id: 'hero_2',
    sub: 'ChatGPT Plus, Gemini Advanced & 4K Cinema',
    title: 'AI Models & 4K Streaming Hub',
    tag: 'VERIFIED OFFICIAL ACCOUNTS',
    bgImage: '/images/hero-ai-cinema.jpg',
    ctaText: 'View AI Tools',
    ctaLink: '#catalog',
    order: 2,
  },
  {
    id: 'hero_3',
    sub: 'Cursor Pro, Claude 3.5 & Developer Workspaces',
    title: 'Pro Developer & Cloud Suites',
    tag: 'FAST CLOUD SERVERS',
    bgImage: '/images/hero-dev-code.jpg',
    ctaText: 'Browse Dev Tools',
    ctaLink: '#catalog',
    order: 3,
  },
  {
    id: 'hero_4',
    sub: 'Adobe Creative Cloud & NordVPN Complete',
    title: 'Creative Design & Security Suites',
    tag: '100% REPLACEMENT WARRANTY',
    bgImage: '/images/hero-creative-vpn.jpg',
    ctaText: 'Discover Creative Apps',
    ctaLink: '#catalog',
    order: 4,
  },
];


